### ISSUE TITLE
import error: "cannot import TextFace from ete3"

### ISSUE THREAD

**Issue by LzhinFdu** [princeton-nlp/NLProofS#2]
Thanks for your generous sharing of this excellent work, which I am very interested in.
But when I try to run the code, I get the error "**can not import TextFace from ete3**". I am the first time to use "ete3" and I find that a lot of people had the same error as me. I tried the solutions mentioned in [https://github.com/etetoolkit/ete/issues/195]("https://github.com/etetoolkit/ete/issues/195") and tried different installation methods given by the official, but none of them worked. 

I would like to ask if you have encountered a similar problem and how to solve it?

I used **Miniconda3 Linux 64-bit** and created a new conda environment using **nlproofs.yaml**.

Below is my error message:
` File "/root/NLProofS/prover/evaluate.py", line 9, in <module>
    from ete3 import TextFace, TreeStyle, NodeStyle
ImportError: cannot import name 'TextFace' from 'ete3' (/root/miniconda3/envs/nlproofs/lib/python3.9/site-packages/ete3/__init__.py)`

**Comment by yangky11** [comment]
Thanks for your interest in our work! 

It could be an issue with the version of ete3. Could you double-check if you're using `ete3==3.1.2`?
```
In [3]: import ete3

In [4]: ete3.__version__
Out[4]: '3.1.2'
``` 

Also, `from ete3 import TextFace, TreeStyle, NodeStyle` is only for visualizing the proofs and is not required for training and evaluation. So a temporary workaround would be just to remove this line (along with the code in evaluate.py that depends on this line).

**Comment by LzhinFdu** [comment]
Thanks for your suggestion!

yeah I have checked the version of "ete3" is 3.1.2. It seems that the cause of this problem is not on the version of "ete3". It's weird. Many people have encountered this problem, but the official did not give a suitable solution. I will try to skip this function later.

**Comment by yangky11** [comment]
Could you please try the [fix-ete3](https://github.com/princeton-nlp/NLProofS/tree/fix-ete3) branch and let me know if that solves the problem?

**Comment by LzhinFdu** [comment]
I still got an error as follows:
`File "/root/NLProofS_ete3/prover/evaluate.py", line 200, in <module>
def get_tree_style(proof: str, score: Optional[float], is_gt: bool) -> TreeStyle:
NameError: name 'TreeStyle' is not defined`

**Comment by yangky11** [comment]
I just fixed that. Try again?

**Comment by LzhinFdu** [comment]
It seems to be working fine. Thanks for your help! : )

**Comment by yangky11** [comment]
You're welcome.

I just merged it into the `main` branch.
