### ISSUE TITLE
Intermediate-F1 & AllCorrect

### ISSUE THREAD

**Issue by varuniyer** [princeton-nlp/NLProofS#6]
When running `python main.py --python main.py test --config cli_task1_single_shot_t5-large.yaml --ckpt_path PROVER_PATH`, I only get results for the proof, leaves, and steps. The paper reports intermediate results as well. How are these obtained?

**Comment by yangky11** [comment]
Hi,

As the README explains:

> Validation and testing results are saved as ./prover/lightning_logs/EXP_ID/results_val.tsv and ./prover/lightning_logs/EXP_ID/results_test.tsv. They are the input to the [EntailmentBank's official evaluation code](https://github.com/allenai/entailment_bank/tree/71385b6d7cc42ac394006bc2fe84d5bd1117f9ac) for calculating the evaluation metrics.
