### ISSUE TITLE
Query regarding the Prover Checkpoints

### ISSUE THREAD

**Issue by SachinVashisth** [princeton-nlp/NLProofS#7]
Hi

It is given in the readme file that for testing NLProofS (stepwise prover + verifier-guided search) on task2 of EntailmentBank dataset, we can use the following command:
`python main.py test --config cli_task2_stepwise_t5-large.yaml --ckpt_path PATH_TO_PROVER_CKPT --model.verifier_weight 0.5 --model.verifier_ckpt PATH_TO_VERIFIER_CKPT --model.proof_search true`

I looked into the `model.py` file in the `prover` folder, where line `147` is:
`self.seq2seq = T5ForConditionalGeneration.from_pretrained(model_name)`
Here, `model_name` is `t5-large` taken from the `yaml` file but I don't see the checkpoints of the prover getting loaded in this class. Can you please tell me where the prover checkpoints are loaded?

**Comment by yangky11** [comment]
`--ckpt_path` is a built-in argument in PyTorch Lightning. I believe it will somehow be passed to the `ckpt_path ` parameter of [Trainer.test](https://lightning.ai/docs/pytorch/stable/common/trainer.html#test). The model-loading logic is implemented by PyTorch Lightning Trainer.

**Comment by SachinVashisth** [comment]
Hi, I solved the problem already.

Anyways, thanks for replying.
